---
- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages dependencies
  apt:
    name: 
        - gpg
        - dirmngr
        - python3
        - python3-pip
        - libpq-dev
        - python3-dev
    state: present

- name: Install pip packages
  pip:
    name:
        - psycopg2

- name: Add an Apt signing key postgresql
  apt_key:
    url: "{{ __postgresql_key }}"
    state: present
  when: 
   - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add an Apt signing key timescaledb    
  apt_key:
    url: "{{ __postgresql_key_time }}"
    state: present
  when: 
   - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install repo postgresql
  apt_repository:
    repo: "{{ __postgresql_repo }}"
    state: present
    update_cache: true
  when: 
   - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 

- name: Install repo timescaledb
  apt_repository:
    repo: "{{ __timescaledb_repo }}"
    state: present
    update_cache: true

- name: PostgreSQL packages are installed.
  apt:
    name: "{{ __postgresql_packages }}"
    state: present

- name: PostgreSQL packages are installed.
  apt:
    name: "{{ __postgresql_packages_timescale }}"
    state: present

- name: Execute timescaledb-tune
  shell: |
   timescaledb-tune --quiet --yes
  notify: restart postgresql

- name: High max_connections
  lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: '^max_connections '
    insertafter: '^#max_connections'
    line: max_connections = 50
  notify: restart postgresql
 