---
# Variable configuration.
- include_tasks: variables.yml

- include_tasks: RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- name: Postgresql | Create a new pass for zabbix user
  command: openssl rand -base64 10
  register: db_zabbix_pass

- name: Postgresql | Display new pass in playbook output
  debug:
      msg: "New zabbix pass: {{db_zabbix_pass.stdout}}"
  when: 
    - db_zabbix_pass.changed