---
- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true

- name: Install packages
  yum:
    name:
        - epel-release
        - openssl
        - python3
        - python3-pip
    state: present

- name: Update pip packages
  pip:
    name:
        - setuptools
        - pip
    state: latest

- name: Install pip packages
  pip:
    name:
        - psycopg2

- name: Install Key-repo
  rpm_key:
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

- name: Install postgresql Repo.
  dnf:
   name: "{{ postgresql_enablerepo }}"
   state: present

- name: Install timescaledb Repo.
  yum_repository:
    name: "timescale_timescaledb"
    description: Timescaledb Official Repository - $basearch
    baseurl: "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/$basearch"
    gpgcheck: 0
    enabled: 1
    gpgkey: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    state: "present"

- name: Disable package postgresql
  command: dnf module disable postgresql -y

- name: PostgreSQL packages are installed.
  dnf:
    name:
      - postgresql{{ postgresql_version }}-server
      - postgresql{{ postgresql_version }}
      - timescaledb-2-postgresql-{{ postgresql_version }}
    state: present

- name: PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }} initdb"
  ignore_errors: true



