---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Ubuntu"
  with_items:
    - deb-src
    - deb

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Debian"
  with_items:
    - deb-src
    - deb

- name: Install Zabbix packeges
  apt:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-nginx-conf
    - zabbix-web-{{ zabbix_server_database }}
    - zabbix-get
    - zabbix-agent

- name: Make sure php service is running
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: Copy php.zabbix.conf template 
  template:
    src: zabbix-php.conf.j2
    dest: /etc/php-fpm.d/zabbix.conf
  notify: restart php

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy zabbix.conf template 
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php

- name: Copy web.zabbix.conf template 
  template:
    src: zabbix_web.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf

- name: Copy nginx.conf template 
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/zabbix/web/zabbix.conf.php
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    owner: root
    group: root
    state: link
  when: 
   - zabbix_version is version_compare('5.4', '>=')

- name: Restart nginx
  service:
    name: nginx
    state: restarted
 