- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  
- name: Install Zabbix packeges
  yum:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-nginx-conf
    - zabbix-web-mysql
    - zabbix-get
    - zabbix-agent

- name: Make sure php service is running
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: Copy php.zabbix.conf template 
  template:
    src: templates/zabbix-php.conf.j2
    dest: /etc/zabbix/php-fpm.conf
  notify: restart php

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy web.zabbix.conf template 
  template:
    src: zabbix_web.conf.j2
    dest: /etc/zabbix/nginx.conf

- name: Copy nginx.conf template 
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'  

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/zabbix/web/zabbix.conf.php
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    owner: root
    group: root
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted