- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Set Mysql root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    host: '%'
    name: 'root'
    password: '{{ mysql_password_root }}'
    priv: "*.*:ALL,GRANT"
    state: present
  ignore_errors: true
