zabbix_version: 4.4
zbx_database_name: zabbix
zbx_database_user: zabbix
zbx_database_address: localhost
zbx_server_address: localhost
zbx_server_ip_ha: localhost
zbx_front_address: localhost
mysql_root_username: root
mysql_root_pass: Tg0z64OVddNzFwNA==
db_zabbix_pass: Tg0z64OVNzFwNA==
zbx_user_privileges: localhost
mysql_repo: mysql

# Databases.
mysql_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1
# Users.
mysql_users: []
#   - name: example
#     host: 127.0.0.1
#     password: secret
#     priv: *.*:USAGE
