---
- name: Install Banco
  hosts: zabbix
  become: yes
  roles:
  - mysql

- name: Install Zabbix Server
  hosts: zabbix
  become: yes
  roles:
  - zabbix-server

- name: Install Front
  hosts: zabbix
  become: yes
  roles:
  - zbx-front