---
- name: Install Banco
  hosts: dbservers
  become: yes
  roles:
  - mysql

- name: Install Zabbix Server
  hosts: server
  become: yes
  roles:
  - zabbix-server

- name: Install Front
  hosts: webservers
  become: yes
  roles:
  - zbx-front