---
- hosts: all
  become: true
  vars:
    zabbix_version: 6.0
    zabbix_server_database: mysql
    zabbix_server_database_long: mysql
  roles:
    - {role: roles/mysql}
    - {role: roles/zabbix-server}
    - {role: roles/zabbix-front}