---
- hosts: all
  become: true
  vars:
    zabbix_version: 7.0
    zabbix_server_database: pgsql
    zabbix_server_database_long: pgsql
    postgresql_version: 17
  roles:
    - {role: ../roles/postgresql}
    - {role: ../roles/zabbix-server}
    - {role: ../roles/zabbix-front}