---
- hosts: all
  vars:
    zabbix_version: 5.0
    zabbix_server_database_long: pgsql
    zabbix_server_database: pgsql
  become: true
  roles:
    - {role: roles/postgresql}
    - {role: roles/zabbix-server}
    - {role: roles/zabbix-front}