---
- name: Install Banco mysql
  hosts: zabbix   
  become: true
  roles:
  - mysql

- name: Install Zabbix Server
  hosts: zabbix
  become: true
  roles:
  - zabbix-server

- name: Install Front
  hosts: zabbix
  become: true
  roles:
  - zbx-front