---
- name: Install Banco
  hosts: db
  become: yes
  roles:
  - mysql

- name: Install Zabbix Server
  hosts: zbx
  become: yes
  roles:
  - zabbix-server

- name: Install Front
  hosts: web
  become: yes
  roles:
  - zbx-front