---
- hosts: all
  vars:
    zabbix_version: 4.4
    zabbix_server_database_long: mysql
    zabbix_server_database: mysql
  become: true
  roles:
    - {role: roles/mysql}
    - {role: roles/zabbix-server}
    - {role: roles/zabbix-front}