- name: Debug IPv4
  debug: 
    msg: "{{ ansible_ssh_host }} {{ ansible_default_ipv4.address }} {{ ansible_all_ipv4_addresses[0] }} {{ ansible_lo.ipv4.address }} {{ zbx_server_address }} {{ zbx_frontend_address }} {{ zbx_database_address }}"

- name: Disable SELinux
  selinux:
    state: disabled
    
- name: Install packages
  yum:
    name:
        - epel-release
        - net-tools
        - vim
        - nano
        - wget
        - telnet
        - rsync
        - git
        - python36
    state: present

- name: Install pip packages
  pip:
    name:
        - pymysql
