- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy zabbix.conf template 
  template:
    src: templates/zabbix.conf.j2
    dest: /etc/php-fpm.d/zabbix.conf
    
- name: Restart php and enable boot
  service: name=php-fpm state=restarted enabled=yes

- name: Copy web.zabbix.conf template 
  template:
    src: templates/zabbix_web.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
  notify: restart nginx

#- name: Start firewall
#  service: 
#    name: firewalld
#    state: started

#- name: Create firewall rule
#  firewalld:
#   port: 80/tcp
#    permanent: yes
#    immediate: yes
#    state: enabled

#- name: Firewalld reload
#  command: firewall-cmd --reload
