- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'
  notify: restart nginx

- name: Copy zabbix.conf template 
  template:
    src: templates/zabbix.conf.j2
    dest: /etc/php-fpm.d/zabbix.conf

- name: Make sure php service is running
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes

- name: Copy web.zabbix.conf template 
  template:
    src: templates/zabbix_web.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
  notify: restart nginx

