---
__postgresql_version: "13"
__postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
__postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
__postgresql_key: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
__postgresql_key_time: "https://packagecloud.io/timescale/timescaledb/gpgkey"
__postgresql_repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
__timescaledb_repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main"
__postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-contrib
  - libpq-dev
__postgresql_packages_timescale:
  - timescaledb-2-postgresql-{{ postgresql_version }}