---
__postgresql_version: "12"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: postgresql
__timescaledb_repo: "ppa:timescale/timescaledb-ppa"
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - timescaledb-postgresql-{{ __postgresql_version }}