---
- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Only run update
  apt:
    update_cache: yes
    upgrade: yes

- name: Add an Apt signing key zabbix
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Ubuntu"
  with_items:
    - deb-src
    - deb

- name: Install repo zabbix
  apt_repository:
    repo: "{{ item }} https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian {{ ansible_distribution_release }} main"
    state: present
  when: 
   - zabbix_repo == "zabbix"
   - ansible_distribution == "Debian"
  with_items:
    - deb-src
    - deb
    
- name: Install Zabbix packeges
  apt:
    name: "{{ packeges }}"
  vars:
    packeges:
    - zabbix-nginx-conf
    - zabbix-frontend-php
    - zabbix-get
    - zabbix-agent

- name: Remove apache
  apt:
    name: apache2
    state: absent

- name: Ensure a locale exists
  locale_gen:
    name: en_US
    state: present
  when:
    - ansible_distribution == 'Debian' 

- name: php-pgsql | Install Zabbix packeges
  apt:
    name: php7.4-pgsql
  when:
    - zabbix_server_database == 'pgsql'

- name: Copy php.zabbix.conf template 
  template:
    src: zabbix-php.conf.j2
    dest: /etc/zabbix/php-fpm.conf

- name: Make sure php service is running
  systemd:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  when: 
    - ansible_distribution_file_variety == 'Debian' and ansible_distribution_major_version <= '20'

- name: Make sure php service is running
  systemd:
    name: php8.1-fpm
    state: restarted
    enabled: yes
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '22'

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy zabbix.conf template 
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php

- name: Copy web.zabbix.conf template 
  template:
    src: zabbix_web.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
  
- name: Copy default template 
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/zabbix/web/zabbix.conf.php
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    owner: root
    group: root
    state: link
  when: 
   - zabbix_version is version_compare('5.4', '>=')

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Copy zabbix_agent.conf template 
  template:
    src: zabbix_agentd.conf.44.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent