---
- include_tasks: RedHat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- name: Set timezone to America/Sao_Paulo
  timezone:
    name: America/Sao_Paulo