---
- name: Install Banco
  hosts: mysql
  vars:
    mysql_password_root: default123
  become: yes
  roles:
  - mysql

- name: Install Zabbix Server
  hosts: zabbix
  vars:
    zbx_server_address: localhost
    zbx_database_address: localhost
    zbx_database_password: default123
    mysql_password_root: default123
    zbx_database_user_root: root
  become: yes
  roles:
  - zabbix-server

- name: Install Front
  hosts: front
  vars:
    zbx_database_address: localhost
    zbx_server_address: localhost
    zbx_database_port: 3306
    zbx_database_password: default123
    pass_zabbix: zabbix2021
  become: yes
  roles:
  - zbx-front
