- name: Install packages dependencies
  apt:
    name:
        - net-tools
        - vim
        - wget
        - telnet
        - rsync
        - git
        - python3
        - python3-pip
    state: present

- name: Install mariadb-server
  apt:
    name: 
        - mariadb-server

- name: Make sure mariadb service is running
  systemd:
    name: mariadb
    state: started
    enabled: yes  

- name: Install pip packages
  pip:
    name:
        - pymysql
    executable: pip3

- name: MariaDB | Create a new pass for zabbix user
  command: openssl rand -base64 8
  register: db_zabbix_pass

- name: MariaDB | Display new pass in playbook output
  debug:
      msg: "New zabbix pass: {{db_zabbix_pass.stdout}}"
  when: 
    - db_zabbix_pass.changed

- name: MariaDB | Publish file .my.cnf in the root home
  template:
      src: user.root.my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600
      force: no

- name: Set Mysql root Password
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    login_unix_socket: "{{ item.login_unix_socket | default('/var/run/mysqld/mysqld.sock') }}" 
    priv: "{{ item.priv | default('priv: *.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_root_users }}"
  #no_log: true
  #ignore_errors: true

