- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Set Mysql root Password
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('priv: *.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: true
  ignore_errors: true

