- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true
    
- name: Install packages
  yum:
    name:
        - epel-release
        - net-tools
        - vim
        - wget
        - openssl
        - telnet
        - rsync
        - git
        - python36
    state: present

- name: Install pip packages
  pip:
    name:
        - pymysql
 
- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Mysql | Create a new pass for zabbix user
  command: openssl rand -base64 10
  register: db_zabbix_pass

- name: Mysql | Display new pass in playbook output
  debug:
      msg: "New zabbix pass: {{db_zabbix_pass.stdout}}"
  when: 
    - db_zabbix_pass.changed

- name: Set Mysql root Password
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('priv: *.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_root_users }}"
  no_log: true

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  user.root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
    force: no
