- name: Disable SELinux
  selinux:
    state: disabled
  ignore_errors: true
    
- name: Install packages
  yum:
    name:
        - epel-release
        - net-tools
        - openssl
        - telnet
        - python3
        - python3-pip
    state: present

- name: Install pip packages
  pip:
    name:
        - pymysql
 
- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL and enable on boot
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Set Mysql root Password
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('priv: *.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_root_users }}"
  no_log: true
  ignore_errors: true

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  user.root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
    force: no
