- name: Create Zabbix server MySQL user
  mysql_user:
    login_host: "{{ item.login_host | default('localhost')}}"
    login_user: "{{ item.login_user | default('root')}}"
    login_password: "{{ item.login_password | default('')}}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  when: zabbix_database_creation
  no_log: true

- name: Create a new database for Zabbix Server
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
    login_host: "{{ item.login_host | default('localhost')}}"
    login_user: "{{ item.login_user | default('root')}}"
    login_password: "{{ item.login_password | default('')}}"
  with_items: "{{ mysql_databases }}"
  when: zabbix_database_creation
  no_log: true

- name: "Get the file for schema.sql"
  shell: ls -1 {{ datafiles_path }}/schema.sql.gz
  changed_when: False
  when:
    - zabbix_database_sqlload
  register: ls_output_create

- name: Import database Zabbix
  mysql_db:
    login_host: "{{ item.login_host | default('localhost')}}"
    login_user: "{{ item.login_user | default('root')}}"
    login_password: "{{ item.login_password | default('')}}"
    name: "{{ item.name }}"
    state: import
    target: "{{ ls_output_create.stdout }}"
  with_items: "{{ mysql_databases }}"
  when:
    - zabbix_database_sqlload
    - zabbix_database_creation
  no_log: true
  ignore_errors: true
