- name: "Get the file for schema.sql"
  shell: ls -1 {{ datafiles_path }}/create.sql.gz
  changed_when: False
  when:
    - zabbix_database_sqlload
  register: ls_output_create

- name: Import database Zabbix
  mysql_db:
    login_host: "{{ item.login_host | default('localhost')}}"
    login_user: "{{ item.login_user | default('root')}}"
    login_password: "{{ item.login_password | default('')}}"
    name: "{{ item.name | default('zabbix') }}"
    state: import
    target: "{{ ls_output_create.stdout }}"
  with_items: "{{ mysql_databases_import }}"
  when:
    - zabbix_database_sqlload
    - zabbix_database_creation
  no_log: true
  ignore_errors: true
