- name: Install dependencies
  pip:
    name:
      - pyzabbix
      - zabbix-api
    executable: pip3

- name: Create auto-registration
  community.zabbix.zabbix_action:
    server_url: http://{{ ansible_ssh_host }}/
    login_user: Admin
    login_password: "{{ pass_zabbix }}"
    name: "Auto registro Linux"
    event_source: 'auto_registration'
    state: present
    status: enabled
    esc_period: 60s
    conditions:
      - type: 'host_metadata'
        operator: 'like'
        value: 'os-linux'
    operations:
      - type: add_host
      - type: add_to_host_group
        host_groups: "Linux servers"
      - type: remove_from_host_group
        host_groups: "Discovered hosts"
      - type: link_to_template
        templates: "Linux by Zabbix agent"
