- name: restart mysql
  service:
    name: mysqld
    state: restarted
- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
- name: restart nginx
  service:
    name: nginx
    state: restarted