- name: restart mysql
  service:
    name: mysqld
    state: restarted
- name: restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
- name: restart httpd
  service:
    name: httpd
    state: restarted