# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
#'rocky-srv' => {'memory' => '1024', 'cpus' => '1', 'ip' => '12', 'box' => 'rockylinux/8'},
'pgsql' => {'memory' => '2024', 'cpus' => '2', 'ip' => '10', 'box' => 'almalinux/8'},
'zabbix-server' => {'memory' => '2024', 'cpus' => '2', 'ip' => '11', 'box' => 'almalinux/8'},
'zabbix-front' => {'memory' => '2024', 'cpus' => '2', 'ip' => '12', 'box' => 'almalinux/8'},
#'debian-srv' => {'memory' => '2024', 'cpus' => '2', 'ip' => '13', 'box' => 'debian/bullseye64'},
#'ubuntu-srv' => {'memory' => '2024', 'cpus' => '2', 'ip' => '14', 'box' => 'ubuntu/jammy64'},
#'debian-srv' => {'memory' => '2024', 'cpus' => '2', 'ip' => '14', 'box' => 'debian/bookworm64'},
}

Vagrant.configure('2') do |config|
  vms.each do |name, conf|
     config.vm.define "#{name}" do |my|
       my.vm.box = conf['box']
       my.vm.hostname = "#{name}.example.com"
       #my.disksize.size = '30GB'
       my.vm.network 'private_network', ip: "172.16.33.#{conf['ip']}"
       my.vm.provision "ansible" do |ansible|
          ansible.playbook = "../zabbix_mult.yml"
          ansible.groups = {
            "db" => ["pgsql"],
            "server" => ["zabbix-server"],
            "front" => ["zabbix-front"],
          }
          ansible.extra_vars = {
            ansible_user: "vagrant"
          }
       end
       my.vm.provider 'virtualbox' do |vb|
          vb.memory = conf['memory']
          vb.cpus = conf['cpus']
       end
     end
  end
end

